// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_Microsoft_MixedReality_EyeTracking_1_H
#define WINRT_Microsoft_MixedReality_EyeTracking_1_H
#include "winrt/impl/Microsoft.MixedReality.EyeTracking.0.h"
WINRT_EXPORT namespace winrt::Microsoft::MixedReality::EyeTracking
{
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTracker :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTracker>
    {
        IEyeGazeTracker(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTracker(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTrackerFrameRate :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTrackerFrameRate>
    {
        IEyeGazeTrackerFrameRate(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTrackerFrameRate(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTrackerRawValues :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTrackerRawValues>
    {
        IEyeGazeTrackerRawValues(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTrackerRawValues(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTrackerRawValuesStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTrackerRawValuesStatics>
    {
        IEyeGazeTrackerRawValuesStatics(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTrackerRawValuesStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTrackerReading :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTrackerReading>
    {
        IEyeGazeTrackerReading(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTrackerReading(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEyeGazeTrackerWatcher :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEyeGazeTrackerWatcher>
    {
        IEyeGazeTrackerWatcher(std::nullptr_t = nullptr) noexcept {}
        IEyeGazeTrackerWatcher(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
