
function data = unpack_pv(response, mode, image_size)
if (response.status == 0)
    if (mode == hl2ss.stream_mode.MODE_1)
        pose = response.pose; 
    else
        pose = zeros([4, 4], 'single');
    end

    data = struct('frame_index', response.frame_index, ...
                  'status',      response.status,      ...
                  'timestamp',   response.timestamp,   ...
                  'image',       response.image,       ...
                  'intrinsics',  response.intrinsics,  ...
                  'exposure',    response.exposure,    ...
                  'imaging',     response.imaging,     ...
                  'gains',       response.gains,       ...
                  'pose',        pose);
else
    data = struct('frame_index', response.frame_index,            ...
                  'status',      response.status,                 ...
                  'timestamp',   zeros([1, 1],         'uint64'), ...
                  'image',       zeros(image_size,     'uint8' ), ...
                  'intrinsics',  zeros([4, 1],         'single'), ...
                  'exposure',    zeros([3, 1],         'uint64'), ...
                  'imaging',     zeros([4, 1],         'uint32'), ...
                  'gains',       zeros([5, 1],         'single'), ...
                  'pose',        zeros([4, 4],         'single'));
end
end
