
function data = unpack_eet(response)
if (response.status == 0)
    data = struct('frame_index',       response.frame_index,       ...
                  'status',            response.status,            ...
                  'timestamp',         response.timestamp,         ...
                  'combined_ray',      response.combined_ray,      ...
                  'left_ray',          response.left_ray,          ...
                  'right_ray',         response.right_ray,         ...
                  'left_openness',     response.left_openness,     ...
                  'right_openness',    response.right_openness,    ...
                  'vergence_distance', response.vergence_distance, ...
                  'valid',             response.valid,             ...
                  'pose',              response.pose);
else
    zero_ray = zeros([6, 1], 'single');
    zero_lrv = zeros([1, 1], 'single');

    data = struct('frame_index',       response.frame_index,            ...
                  'status',            response.status,                 ...
                  'timestamp',         zeros([1, 1],         'uint64'), ...
                  'combined_ray',      zero_ray,                        ...
                  'left_ray',          zero_ray,                        ...
                  'right_ray',         zero_ray,                        ...
                  'left_openness',     zero_lrv,                        ...
                  'right_openness',    zero_lrv,                        ...
                  'vergence_distance', zero_lrv,                        ...
                  'valid',             zeros([1, 1],         'uint32'), ...
                  'pose',              zeros([4, 4],         'single'));
end
end
