
function data = unpack_rm_vlc(response, mode)
if (response.status == 0)
    if (mode == hl2ss.stream_mode.MODE_1)
        pose = response.pose; 
    else
        pose = zeros([4, 4], 'single');
    end

    data = struct('frame_index', response.frame_index, ...
                  'status',      response.status,      ...
                  'timestamp',   response.timestamp,   ...
                  'image',       response.image,       ...
                  'pose',        pose);
else
    image_size = [hl2ss.parameters_rm_vlc.HEIGHT, hl2ss.parameters_rm_vlc.WIDTH];
    
    data = struct('frame_index', response.frame_index,            ...
                  'status',      response.status,                 ...
                  'timestamp',   zeros([1, 1],         'uint64'), ...
                  'image',       zeros(image_size,     'uint8' ), ...
                  'pose',        zeros([4, 4],         'single'));
end
end
