
function data = unpack_extended_depth(response, mode, image_size)
if (response.status == 0)
    data = struct('frame_index', response.frame_index, ...
                  'status',      response.status,      ...
                  'timestamp',   response.timestamp,   ...
                  'depth',       response.depth);
else
    data = struct('frame_index', response.frame_index,            ...
                  'status',      response.status,                 ...
                  'timestamp',   zeros([1, 1],         'uint64'), ...
                  'depth',       zeros(image_size,     'uint16'));
end
end
