
function data = unpack_rm_imu(response, mode, image_size)
if (response.status == 0)
    if (mode == hl2ss.stream_mode.MODE_1)
        pose = response.pose; 
    else
        pose = zeros([4, 4], 'single');
    end

    data = struct('frame_index',      response.frame_index,      ...
                  'status',           response.status,           ...
                  'timestamp',        response.timestamp,        ...
                  'sensor_timestamp', response.sensor_timestamp, ...
                  'host_timestamp',   response.host_timestamp,   ...
                  'x',                response.x,                ...
                  'y',                response.y,                ...
                  'z',                response.z,                ...
                  'temperature',      response.temperature,      ...
                  'pose',             pose);
else
    zero_image_u64 = zeros(image_size, 'uint64');
    zero_image_f32 = zeros(image_size, 'single');

    data = struct('frame_index',      response.frame_index,            ...
                  'status',           response.status,                 ...
                  'timestamp',        zeros([1, 1],         'uint64'), ...
                  'sensor_timestamp', zero_image_u64,                  ...
                  'host_timestamp',   zero_image_u64,                  ...
                  'x',                zero_image_f32,                  ...
                  'y',                zero_image_f32,                  ...
                  'z',                zero_image_f32,                  ...
                  'temperature',      zero_image_f32,                  ...
                  'pose',             zeros([4, 4],         'single'));
end
end
