
function data = unpack_si(response)
if (response.status == 0)
    data = struct('frame_index', response.frame_index, ...
                  'status',      response.status,      ...
                  'timestamp',   response.timestamp,   ...
                  'valid',       response.valid,       ...
                  'head_pose',   response.head_pose,   ...
                  'eye_ray',     response.eye_ray,     ...
                  'left_hand',   response.left_hand,   ...
                  'right_hand',  response.right_hand);
else
    zero_hand = zeros([9, 26], 'single');

    data = struct('frame_index', response.frame_index,            ...
                  'status',      response.status,                 ...
                  'timestamp',   zeros([1, 1],         'uint64'), ...
                  'valid',       zeros([1, 1],         'uint32'), ...
                  'head_pose',   zeros([3, 3],         'single'), ...
                  'eye_ray',     zeros([6, 1],         'single'), ...
                  'left_hand',   zero_hand,                       ...
                  'right_hand',  zero_hand);
end
end
