
mex -v C:\Users\jcds\Documents\GitHub\hl2ss\extensions\client_matlab\hl2ss_matlab.cpp ...
    C:\Users\jcds\Documents\GitHub\hl2ss\extensions\client_cpp\hl2ss.cpp ...
    C:\Users\jcds\Documents\GitHub\hl2ss\extensions\client_cpp\hl2ss_lnm.cpp ...
    C:\Users\jcds\Documents\GitHub\hl2ss\extensions\client_cpp\hl2ss_mt.cpp ...
    -DWIN32 ...
    -IC:/Users/jcds/Documents/GitHub/hl2ss/extensions/client_cpp ...
    -IC:/Users/jcds/SDK/ffmpeg-master-latest-win64-gpl-shared/include ...
    -IC:/Users/jcds/SDK/opencv/build/include ...
    -LC:/Users/jcds/SDK/opencv/build/x64/vc16/lib ...
    -LC:/Users/jcds/SDK/ffmpeg-master-latest-win64-gpl-shared/lib/ ...
    -lopencv_world480 ...
    -lavcodec ...
    -lavutil ...
    -lWs2_32