
ffmpeg_path = 'C:/Users/jcds/SDK/ffmpeg-master-latest-win64-gpl-shared';
opencv_path = 'C:/Users/jcds/SDK/opencv/build';

mex('hl2ss_matlab.cpp', ...
    '../client_cpp/hl2ss.cpp', ...
    '../client_cpp/hl2ss_lnm.cpp', ...
    '../client_cpp/hl2ss_mt.cpp', ...
    '../../3rdparty/Zdepth/src/*.cpp', ...
    '../../3rdparty/Zdepth/zstd/src/*.c', ...
    '-DWIN32', ...
    '-DHL2SS_ENABLE_ZDEPTH', ...
    '-I../client_cpp', ...
    ['-I' ffmpeg_path '/include'], ...
    ['-I' opencv_path '/include'], ...
    '-I../../3rdparty/Zdepth/include', ...
    '-I../../3rdparty/Zdepth/zstd/include', ...
    ['-L' opencv_path '/x64/vc16/lib'], ...
    ['-L' ffmpeg_path '/lib/'], ...
    '-lopencv_world480', ...
    '-lavcodec', ...
    '-lavutil', ...
    '-lWs2_32' ...
    );
