
% Using the MEX library on Ubuntu currently requires
% export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libtiff.so
% matlab -softwareopengl

mex('hl2ss_matlab.cpp', ...
    '../client_cpp/hl2ss.cpp', ...
    '../client_cpp/hl2ss_lnm.cpp', ...
    '../client_cpp/hl2ss_mt.cpp', ...
    '../../3rdparty/Zdepth/src/*.cpp', ...
    '../../3rdparty/Zdepth/zstd/src/*.c', ...
    '-DHL2SS_ENABLE_ZDEPTH', ...
    '-I../client_cpp', ...
    '-I../../3rdparty/Zdepth/include', ...
    '-I../../3rdparty/Zdepth/zstd/include', ...
    '-I../../3rdparty/Zdepth/zstd/src', ...
    '-L/usr/local/lib', ...
    '-lopencv_highgui', ...
    '-lopencv_imgcodecs', ...
    '-lopencv_imgproc', ...
    '-lopencv_core', ...
    '-lavcodec', ...
    '-lavutil' ...
);
