
#pragma once

#define PORT_NUMBER_BASE   3800

#define PORT_NUMBER_RM_VLF 3800
#define PORT_NUMBER_RM_VLL 3801
#define PORT_NUMBER_RM_VRF 3802
#define PORT_NUMBER_RM_VRR 3803
#define PORT_NUMBER_RM_ZHT 3804
#define PORT_NUMBER_RM_ZLT 3805
#define PORT_NUMBER_RM_ACC 3806
#define PORT_NUMBER_RM_GYR 3807
#define PORT_NUMBER_RM_MAG 3808
#define PORT_NUMBER_RC     3809
#define PORT_NUMBER_PV     3810
#define PORT_NUMBER_MC     3811
#define PORT_NUMBER_SI     3812
#define PORT_NUMBER_SM     3813
#define PORT_NUMBER_SU     3814
#define PORT_NUMBER_VI     3815
#define PORT_NUMBER_MQ     3816
#define PORT_NUMBER_EET    3817
#define PORT_NUMBER_EA     3818
#define PORT_NUMBER_EV     3819
#define PORT_NUMBER_MQX    3820
#define PORT_NUMBER_EZ     3821

#define X38_HTOA(H)           #H
#define X38_PORT_HTOA(port)   X38_HTOA(port)
#define X38_PORT_OFFSET(port) ((port) - PORT_NUMBER_BASE)

#define PORT_NAME_RM_VLF X38_PORT_HTOA(PORT_NUMBER_RM_VLF)
#define PORT_NAME_RM_VLL X38_PORT_HTOA(PORT_NUMBER_RM_VLL)
#define PORT_NAME_RM_VRF X38_PORT_HTOA(PORT_NUMBER_RM_VRF)
#define PORT_NAME_RM_VRR X38_PORT_HTOA(PORT_NUMBER_RM_VRR)
#define PORT_NAME_RM_ZHT X38_PORT_HTOA(PORT_NUMBER_RM_ZHT)
#define PORT_NAME_RM_ZLT X38_PORT_HTOA(PORT_NUMBER_RM_ZLT)
#define PORT_NAME_RM_ACC X38_PORT_HTOA(PORT_NUMBER_RM_ACC)
#define PORT_NAME_RM_GYR X38_PORT_HTOA(PORT_NUMBER_RM_GYR)
#define PORT_NAME_RM_MAG X38_PORT_HTOA(PORT_NUMBER_RM_MAG)
#define PORT_NAME_RC     X38_PORT_HTOA(PORT_NUMBER_RC)
#define PORT_NAME_PV     X38_PORT_HTOA(PORT_NUMBER_PV)
#define PORT_NAME_MC     X38_PORT_HTOA(PORT_NUMBER_MC)
#define PORT_NAME_SI     X38_PORT_HTOA(PORT_NUMBER_SI)
#define PORT_NAME_SM     X38_PORT_HTOA(PORT_NUMBER_SM)
#define PORT_NAME_SU     X38_PORT_HTOA(PORT_NUMBER_SU)
#define PORT_NAME_VI     X38_PORT_HTOA(PORT_NUMBER_VI)
#define PORT_NAME_MQ     X38_PORT_HTOA(PORT_NUMBER_MQ)
#define PORT_NAME_EET    X38_PORT_HTOA(PORT_NUMBER_EET)
#define PORT_NAME_EA     X38_PORT_HTOA(PORT_NUMBER_EA)
#define PORT_NAME_EV     X38_PORT_HTOA(PORT_NUMBER_EV)
#define PORT_NAME_MQX    X38_PORT_HTOA(PORT_NUMBER_MQX)
#define PORT_NAME_EZ     X38_PORT_HTOA(PORT_NUMBER_EZ)

#define PORT_ID_RM_VLF X38_PORT_OFFSET(PORT_NUMBER_RM_VLF)
#define PORT_ID_RM_VLL X38_PORT_OFFSET(PORT_NUMBER_RM_VLL)
#define PORT_ID_RM_VRF X38_PORT_OFFSET(PORT_NUMBER_RM_VRF)
#define PORT_ID_RM_VRR X38_PORT_OFFSET(PORT_NUMBER_RM_VRR)
#define PORT_ID_RM_ZHT X38_PORT_OFFSET(PORT_NUMBER_RM_ZHT)
#define PORT_ID_RM_ZLT X38_PORT_OFFSET(PORT_NUMBER_RM_ZLT)
#define PORT_ID_RM_ACC X38_PORT_OFFSET(PORT_NUMBER_RM_ACC)
#define PORT_ID_RM_GYR X38_PORT_OFFSET(PORT_NUMBER_RM_GYR)
#define PORT_ID_RM_MAG X38_PORT_OFFSET(PORT_NUMBER_RM_MAG)
#define PORT_ID_RC     X38_PORT_OFFSET(PORT_NUMBER_RC)
#define PORT_ID_PV     X38_PORT_OFFSET(PORT_NUMBER_PV)
#define PORT_ID_MC     X38_PORT_OFFSET(PORT_NUMBER_MC)
#define PORT_ID_SI     X38_PORT_OFFSET(PORT_NUMBER_SI)
#define PORT_ID_SM     X38_PORT_OFFSET(PORT_NUMBER_SM)
#define PORT_ID_SU     X38_PORT_OFFSET(PORT_NUMBER_SU)
#define PORT_ID_VI     X38_PORT_OFFSET(PORT_NUMBER_VI)
#define PORT_ID_MQ     X38_PORT_OFFSET(PORT_NUMBER_MQ)
#define PORT_ID_EET    X38_PORT_OFFSET(PORT_NUMBER_EET)
#define PORT_ID_EA     X38_PORT_OFFSET(PORT_NUMBER_EA)
#define PORT_ID_EV     X38_PORT_OFFSET(PORT_NUMBER_EV)
#define PORT_ID_MQX    X38_PORT_OFFSET(PORT_NUMBER_MQX)
#define PORT_ID_EZ     X38_PORT_OFFSET(PORT_NUMBER_EZ)
